### ISSUE TITLE
ImportError in Python 3.9

### ISSUE THREAD

**Issue by VikasNeha** [tobigue/searcheval#1]
In Python 3.9 if we try to import the modules - 

```
import searcheval.helpers
import searcheval.metrics
```

It throws and `ImportError`.

The very simple fix to this issues is - 

1. Change. `except NameError:` -> `except ImportError:` in `helpers.py` line 7.
2. Change. `except NameError:` -> `except ImportError:` in `metrics.py` line 9.

**Comment by tobigue** [comment]
Thanks! Fix is merged.

**Comment by tobigue** [comment]
Released as version 0.2.2
